### ISSUE TITLE
彩虹多多

### ISSUE THREAD

**Issue by ssh1171266849** [GuoXiCheng/SKIP#266]
有时候能跳过，有时候就打开广告了

**Comment by GuoXiCheng** [comment]
应该不会吧，下面是在我的设备上抓取到的配置，给你参考

```yaml
- appName: 彩虹多多
  packageName: com.cia.hongdows
  skipBounds:
    - bound: 1244,176,1384,316
      activityName: com.fenghuajueli.module_host.LauncherActivity
      file: fileId=2d762f56-5cf9-4ee9-8f84-f6b0c39365e3&nodeId=13
      desc: 开屏广告（无id）
  skipIds:
    - id: com.byted.pangle.m:id/tt_splash_skip_btn
      activityName: com.fenghuajueli.module_host.LauncherActivity
      file: fileId=2ffe5ac4-b353-4d50-b9b1-fbd0d938b5ed&nodeId=14
      desc: 开屏广告（有id）
```
[2ffe5ac4-b353-4d50-b9b1-fbd0d938b5ed.zip](https://github.com/user-attachments/files/17285933/2ffe5ac4-b353-4d50-b9b1-fbd0d938b5ed.zip)

[2d762f56-5cf9-4ee9-8f84-f6b0c39365e3.zip](https://github.com/user-attachments/files/17285994/2d762f56-5cf9-4ee9-8f84-f6b0c39365e3.zip)
