### ISSUE TITLE
B站有漏跳，自行配置无效

### ISSUE THREAD

**Issue by emCupid** [GuoXiCheng/SKIP#295]
[74ecaab9-7014-419e-ae70-731e2aac113f.zip](https://github.com/user-attachments/files/18033995/74ecaab9-7014-419e-ae70-731e2aac113f.zip)
- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipIds:
    - id: tv.danmaku.bili:id/count_down
      bound:  920,2487,1208,2631
      activityName: tv.danmaku.bili.MainActivityV2
      file: fileId=74ecaab9-7014-419e-ae70-731e2aac113f&nodeId=26
      desc: 请填写描述

手点跳过可用，但是程序无法跳过，通过布局检查写配置也没有作用

**Comment by GuoXiCheng** [comment]
```yaml
- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipTexts:
    - text: 跳过
      activityName: tv.danmaku.bili.MainActivityV2
      file: fileId=74ecaab9-7014-419e-ae70-731e2aac113f&nodeId=26
      length: 4
```

**Comment by emCupid** [comment]
> ```yaml
> - appName: 哔哩哔哩
>   packageName: tv.danmaku.bili
>   skipTexts:
>     - text: 跳过
>       activityName: tv.danmaku.bili.MainActivityV2
>       file: fileId=74ecaab9-7014-419e-ae70-731e2aac113f&nodeId=26
>       length: 4
> ```

`- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipTexts:
    - text: 跳过`
 我改成这样了，然后开了提示，不断弹出“已跳过广告”的提示，但是还是没有跳过，计数完了才进入，因为B站很不好抓，不是每次都有开屏，所以反反复复了多次也没广告，我再抓抓看

另外不好意思，还有个问题，如果想精确一些有多个activityName是不是这样写？
`- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipTexts:
    - text: 跳过
      activityName: tv.danmaku.bili.MainActivityV2
      length: 4
    - activityName: com.huawei.android.launcher.unihome.UniHomeLauncher`

我参考了https://skip.guoxicheng.top/advance/custom-config/field-meaning.html和  完整的配置参考  不知道这么写对不对，自己动手才能丰衣足食，不能总做伸手党

**Comment by emCupid** [comment]
[0a74c516-1d04-46fb-b51b-7944b9e9533a.zip](https://github.com/user-attachments/files/18050547/0a74c516-1d04-46fb-b51b-7944b9e9533a.zip)
总算让我抓到了

**Comment by GuoXiCheng** [comment]
`com.huawei.android.launcher.unihome.UniHomeLauncher` 看起来不像B站的

你应该是想这样：

```yaml
- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipIds:
    - id: tv.danmaku.bili:id/count_down
      activityName: tv.danmaku.bili.MainActivityV2
  skipTexts:
    - text: 跳过
      activityName: tv.danmaku.bili.MainActivityV2
      length: 4
```
